# Generated by Django 3.1.5 on 2021-01-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210105_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='label',
            field=models.ManyToManyField(help_text='Select any tags for this note', to='core.Label'),
        ),
    ]
