# Generated by Django 3.1.5 on 2021-01-06 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210106_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='label',
            new_name='labels',
        ),
    ]
