# Generated by Django 3.1.5 on 2021-01-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210106_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='labels',
            field=models.ManyToManyField(help_text='Select any tags for this note', related_name='notes', to='core.Label'),
        ),
    ]
